/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.4.1/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.openjfx)
    application
}

repositories {
    mavenCentral()
}

dependencies {
    implementation(libs.guava)
}

javafx {
    version = "21.0.2"
    modules("javafx.controls", "javafx.fxml")
}

testing {
    suites {
        val test by getting(JvmTestSuite::class) {
            useKotlinTest("2.3.0")
        }
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

kotlin {
    jvmToolchain(17)
}

application {
    mainClass.set("org.example.AppKt")
}
